### ISSUE TITLE
"Issueベース開発"レビュー依頼

### ISSUE THREAD

**Issue by rei-dev99** [rei-dev99/TackleMaster#6]
# 実装予定

## 共通部分
- [ ] アプリケーション雛形作成
- [ ] Docker環境構築
- [ ] README修正
- [ ] 画面遷移図修正
- [ ] ER図修正
- [ ] issue追加・修正
- [ ] デザイン、素材、見せ方について検討
- [ ] CSSフレームワーク決定
- [ ] フロントエンド技術の決定
- [ ] レスポンシブ対応(SP)
- [ ] 必要な技術のキャッチアップなど
- [ ] Rspecテスト必要な箇所
- [ ] 独自ドメイン設定
- [ ] Google Analytics導入
- [ ] デプロイ先の決定
- [ ] 本番環境へデプロイ
- [ ] アプリについてQiita記事を書く

### 機能
- [ ] タックル登録機能(ロッド、リール、ライン、ルアー)
- [ ] タックルの検索機能(自分が登録したタックルの一覧ページを対象に検索)
- [ ] キーワード検索(タックル名やアイテムの名前、種類を入力して検索できる基本的な機能)
- [ ] カテゴリー検索(ロッド、リール、ルアーなど、各カテゴリーに分けて検索できる機能)
- [ ] 最適な釣り具提案機能(OpenAI API)
- [ ] Google認証(Google Identity Platform)

### ページ
- [ ] 新規登録ページ
- [ ] ログインページ
- [ ] パスワード確認ページ
- [ ] パスワード再設定ページ
- [ ] トップページ
- [ ] マイページ(タックル一覧ページ)
- [ ] タックル登録ページ
- [ ] タックル詳細ページ
- [ ] タックルを探すページ(最適な釣具提案機能)
- [ ] タックル結果ページ(最適な釣具提案結果)
- [ ] お問い合わせページ(Google Form)
- [ ] 利用規約
- [ ] プライバシーポリシー

### 機能
- [ ] 登録したタックルをXに共有できる機能
- [ ] 登録したタックルの共有されたタックル一覧ページへの共有機能
- [ ] 共有されたタックルの一覧ページに検索機能
- [ ] 共有されたタックルの一覧ページにいいねする機能
- [ ] 共有されたタックルの一覧ページにコメントする機能
- [ ] 共有されたタックルの一覧ページにお気に入りする機能

### ページ
- [ ] 共有されたタックル一覧ページ
- [ ] 共有されたタックルでいいねした一覧ページ
- [ ] 共有されたタックルでお気に入りにした一覧ページ
- [ ] 最低限の釣具についての知識が学べるページ

## 追加機能検討中
- [ ] タックル登録時に、入力したロッドやリールなどの画像を登録できる機能もしくはamazonの釣具画像を拾う機能(AmazonのAPI)
- [ ] タックル結果ページ(最適な釣具提案結果)を保存できる機能
- [ ] 釣りに行く予定を登録できる機能(釣り場、登録したタックルを追加、日付、通知)
- [ ] 釣り条件に最適な時期推薦機能(ユーザーが狙っている魚種や釣り場所を入力すると、過去のデータや天候予測を基に、最適な釣りの時期や時間をAIが推薦)
- [ ] 釣具の機種比較機能{リールやロッド、ルアーなどの釣具のスペック（重さ、長さ、対象魚種など）や価格、ユーザーレビューを比較。複数の釣具を並べて詳細な情報を比較。}
- [ ] 日付入力で天気予報表示(OpenWeatherMap API)
- [ ] 釣りの予定が近づいてきたらメールで通知する機能(Action MailerもしくはFirebase Cloud Messaging)

**Comment by Tsuchiya2** [comment]
![image](https://github.com/rei-dev99/TackleMaster/assets/61481161/acdb71c0-2d43-42d6-b138-8c875a058d9b)

Projectsにアクセスしましたが、看板・issue・ストーリーポイントが確認できませんでした。カリキュラムをご確認いただいて、上記確認できる状態で提出をお願いいたします。

**Comment by rei-dev99** [comment]
すみません、privateになっていたのでpublicに変更しました。
ご確認よろしくお願いします！

**Comment by tmtkzk0823** [comment]
ご対応ありがとうございます。
Projectsを確認させていただいたところ、画像のようにissueを拝見することができなかった確認していただいてもよろしいでしょうか？
[![Image from Gyazo](https://t.gyazo.com/teams/startup-technology/bcea010e272fe9145659daa62a6672fc.png)](https://startup-technology.gyazo.com/bcea010e272fe9145659daa62a6672fc)

**Comment by rei-dev99** [comment]
ご確認ありがとうございました！

確認したところ、こちらの不手際で、issueを別のprivateになっているリポジトリに設定していたようでした。
新しくProjectを作り直して連携させましたので、そちらご確認よろしくお願いします。

「[Tackle Master開発プロジェクト](https://github.com/users/rei-dev99/projects/3)」

**Comment by tmtkzk0823** [comment]
ご対応ありがとうございます。
確認できました。

ストーリポイントが 5 〜 8 のモノは、issueの粒度として大きいかと思うので分解してみましょう。
理想は1つの機能を実装する際、1 〜 3 のisuueが複数できるのが理想です。（大きくても5）
[#7](https://github.com/rei-dev99/TackleMaster/issues/7)が8でしたので、例として以下に分解したものを記載しておきますね。

```
---------------------------------------------------------
ストーリーポイント: 3~4
 - socery導入
 - form_with
 - バリデーション設定[未記入拒否(presence: true) 
 - 登録内容[ユーザー名、メアド、パスワード、パスワード確認
 - 新規登録後、ログインページへ遷移

---------------------------------------------------------
ストーリーポイント: 3~5

 - Google認証の実装: Google Identity Platform
 
---------------------------------------------------------
 ストーリーポイント: 1~2
- レイアウト見た目

---------------------------------------------------------

**Comment by rei-dev99** [comment]
ありがとうございます！

ご教示くださった通りに、さらにissueを分解してストーリーポイントが最大5になるように設定しました。
それに合わせて、issueもいくつか増やして、1~3程度のストーリーポイントとなるようにしました。

**Comment by tarakish** [comment]
修正確認しました。LGTMです！
開発頑張ってください🔥

**Comment by tarakish** [comment]
こちら不具合のようでした。再度LGTMに変更しましたのでご確認いだけますと幸いです！

**Comment by rei-dev99** [comment]
ありがとうございました！
適用されて、案内が出てきました。

これから頑張ります！！！
